apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: ersti-kit-production
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: ersti-hilfe-kit
  policy:
    numerical:
      order: asc
  filterTags:
    pattern: '^main-([0-9]+)$'
    extract: '$1'